name: Build Native Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: maven
      - name: Build on Linux with mvnw
        if: matrix.os == 'ubuntu-latest'
        run: |
          make build
          zip -r target/kt-cli-app-amd64-linux.zip target/kt-cli-app
      - name: Build on Mac with mvnw
        if: matrix.os == 'macos-latest'
        run: |
          make build
          zip -r target/kt-cli-app-amd64-darwin.zip target/kt-cli-app
      - name: Build on Windows with mvnw.cmd
        if: matrix.os == 'windows-latest'
        run: |
          make build-win
          powershell Compress-Archive -Path .\target\kt-cli-app .\target\kt-cli-app-amd64.zip


